services:
  sistema-ponto-eletronico:
    container_name: sistema-ponto-eletronico
    image: sistema-ponto-eletronico
    build:
      context: .
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped
    stdin_open: true
    tty: true 
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    depends_on:
      - db
    networks:
      - ponto_eletronico_network
  db:
    image: mysql:oraclelinux9
    container_name: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: ponto_eletronico_database
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    networks:
      - ponto_eletronico_network
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    depends_on:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "8080:80"
    networks:
      - ponto_eletronico_network
networks:
  ponto_eletronico_network:
    driver: bridge